// lib/catalogData.ts

export interface ProductItem {
  id: number;
  nameUrdu: string;
  nameEn: string;
  price: number;
  category: "common" | "kashif";
}

export const PRODUCT_CATALOG: ProductItem[] = [
  // --- مشترکہ لسٹ (Common List: 1-57) ---
  { id: 1, nameUrdu: "پیچکس", nameEn: "Screwdriver", price: 12, category: "common" },
  { id: 2, nameUrdu: "شیشہ ٹیپ", nameEn: "Transparent Tape", price: 17, category: "common" },
  { id: 3, nameUrdu: "قینچی", nameEn: "Scissors", price: 19, category: "common" },
  { id: 4, nameUrdu: "ایلفی", nameEn: "Elfy / Super Glue", price: 19, category: "common" },
  { id: 5, nameUrdu: "سوئچ", nameEn: "Electric Switch", price: 13, category: "common" },
  { id: 6, nameUrdu: "بریسلیٹ", nameEn: "Bracelet", price: 17, category: "common" },
  { id: 7, nameUrdu: "کان کے ٹاپس", nameEn: "Ear Tops", price: 9, category: "common" },
  { id: 8, nameUrdu: "کیچر مکس", nameEn: "Hair Catcher Mix", price: 18, category: "common" },
  { id: 9, nameUrdu: "کی ہینگر", nameEn: "Key Hanger", price: 20, category: "common" },
  { id: 10, nameUrdu: "گرین سکوچ", nameEn: "Green Scrim / Scorer", price: 16, category: "common" },
  { id: 11, nameUrdu: "اسکاچ برائٹ", nameEn: "Scotch Brite", price: 21, category: "common" },
  { id: 12, nameUrdu: "کاٹن بڈز", nameEn: "Cotton Buds", price: 16, category: "common" },
  { id: 13, nameUrdu: "چین", nameEn: "Chain", price: 16, category: "common" },
  { id: 14, nameUrdu: "چھیلنے والے (پیلر)", nameEn: "Peeler", price: 17, category: "common" },
  { id: 15, nameUrdu: "اسٹیل جالی", nameEn: "Steel Scrubber", price: 21, category: "common" },
  { id: 16, nameUrdu: "کڈز چوڑی", nameEn: "Kids Bangles", price: 15, category: "common" },
  { id: 17, nameUrdu: "پیکٹ کانٹے", nameEn: "Packet Hair Pins", price: 16, category: "common" },
  { id: 18, nameUrdu: "موبائل اسٹینڈ", nameEn: "Mobile Stand", price: 16, category: "common" },
  { id: 19, nameUrdu: "چٹکی بنڈل", nameEn: "Clothespin Bundle", price: 18, category: "common" },
  { id: 20, nameUrdu: "مہندی عرق", nameEn: "Mehendi Liquid", price: 20, category: "common" },
  { id: 21, nameUrdu: "نمک دانی", nameEn: "Salt Shaker", price: 16, category: "common" },
  { id: 22, nameUrdu: "نمکو ملٹی", nameEn: "Nimko Multi", price: 18, category: "common" },
  { id: 23, nameUrdu: "سٹار پن", nameEn: "Star Hairpin", price: 18, category: "common" },
  { id: 24, nameUrdu: "ربڑ بوتل", nameEn: "Rubber Bottle", price: 15, category: "common" },
  { id: 25, nameUrdu: "نالا", nameEn: "Drawstring (Naala)", price: 18, category: "common" },
  { id: 26, nameUrdu: "سپائڈر جیلی", nameEn: "Spider Jelly Toy", price: 16, category: "common" },
  { id: 27, nameUrdu: "ہاتھ والا پنکھا", nameEn: "Hand Fan", price: 20, category: "common" },
  { id: 28, nameUrdu: "کلاتھ چٹکی", nameEn: "Cloth Clip Single", price: 18, category: "common" },
  { id: 29, nameUrdu: "ربڑ بریسلیٹ", nameEn: "Rubber Bracelet", price: 18, category: "common" },
  { id: 30, nameUrdu: "بڑی بالیاں", nameEn: "Large Hoop Earrings", price: 17, category: "common" },
  { id: 31, nameUrdu: "فنائل", nameEn: "Phenyl", price: 12, category: "common" },
  { id: 32, nameUrdu: "نتھلی", nameEn: "Nose Ring (Nathli)", price: 12, category: "common" },
  { id: 33, nameUrdu: "گلابی برش", nameEn: "Pink Hairbrush", price: 16, category: "common" },
  { id: 34, nameUrdu: "چائے پونی", nameEn: "Tea Strainer", price: 18, category: "common" },
  { id: 35, nameUrdu: "گروئنگ بال", nameEn: "Growing Ball", price: 16, category: "common" },
  { id: 36, nameUrdu: "انچی ٹیپ", nameEn: "Measuring Tape", price: 20, category: "common" },
  { id: 37, nameUrdu: "ٹشو", nameEn: "Tissue Pack", price: 14, category: "common" },
  { id: 38, nameUrdu: "سکول پن", nameEn: "School Safety Pin", price: 13, category: "common" },
  { id: 39, nameUrdu: "الفابیٹ کچین", nameEn: "Alphabet Keychain", price: 11, category: "common" },
  { id: 40, nameUrdu: "کرنسی کیچین", nameEn: "Currency Keychain", price: 10, category: "common" },
  { id: 41, nameUrdu: "پنچنگ بلون", nameEn: "Punching Balloon", price: 14, category: "common" },
  { id: 42, nameUrdu: "لٹو", nameEn: "Spinning Top (Lattu)", price: 8, category: "common" },
  { id: 43, nameUrdu: "بانسری", nameEn: "Flute", price: 8, category: "common" },
  { id: 44, nameUrdu: "سپائڈر ماسک", nameEn: "Spider-Man Mask", price: 12, category: "common" },
  { id: 45, nameUrdu: "سرمہ", nameEn: "Surma", price: 16, category: "common" },
  { id: 46, nameUrdu: "تیل قوم", nameEn: "Hair Oil Comb", price: 16, category: "common" },
  { id: 47, nameUrdu: "چھوٹی کنگھی", nameEn: "Small Comb", price: 9, category: "common" },
  { id: 48, nameUrdu: "سپرنگ ہیر بینڈ", nameEn: "Spring Hair Band", price: 14, category: "common" },
  { id: 49, nameUrdu: "ہیر کیچڑز مکس", nameEn: "Hair Clips Mixed", price: 17, category: "common" },
  { id: 50, nameUrdu: "کلائی بینڈ", nameEn: "Wrist Band", price: 12, category: "common" },
  { id: 51, nameUrdu: "گولک", nameEn: "Money Box (Golak)", price: 12, category: "common" },
  { id: 52, nameUrdu: "سلائم", nameEn: "Slime Toy", price: 20, category: "common" },
  { id: 53, nameUrdu: "تتلی انگوٹھی", nameEn: "Butterfly Ring", price: 10, category: "common" },
  { id: 54, nameUrdu: "نیل پالش", nameEn: "Nail Polish", price: 20, category: "common" },
  { id: 55, nameUrdu: "میٹل کار", nameEn: "Die-Cast Metal Car", price: 21, category: "common" },
  { id: 56, nameUrdu: "صابن دانی", nameEn: "Soap Dish", price: 15, category: "common" },
  { id: 57, nameUrdu: "بڑی کنگھی", nameEn: "Large Comb", price: 16, category: "common" },

  // --- کاشف نعیم لسٹ (Kashif Naeem List: 58-72) ---
  { id: 58, nameUrdu: "پاکٹ کنگھی", nameEn: "Pocket Comb", price: 10, category: "kashif" },
  { id: 59, nameUrdu: "لیڈ پنسل", nameEn: "Lead Pencil", price: 16, category: "kashif" },
  { id: 60, nameUrdu: "لائٹ چھوٹا (S)", nameEn: "Mini LED Light (S)", price: 17, category: "kashif" },
  { id: 61, nameUrdu: "حجاب پن چھوٹا (S)", nameEn: "Hijab Pin Small (S)", price: 19, category: "kashif" },
  { id: 62, nameUrdu: "کویو سیل بڑا (L)", nameEn: "Button Cell Large (L)", price: 14, category: "kashif" },
  { id: 63, nameUrdu: "کویو سیل چھوٹا (S)", nameEn: "Button Cell Small (S)", price: 13, category: "kashif" },
  { id: 64, nameUrdu: "سیفٹی پن", nameEn: "Safety Pin", price: 9, category: "kashif" },
  { id: 65, nameUrdu: "پاپ پاپ", nameEn: "Pop Pop Snappers", price: 23, category: "kashif" },
  { id: 66, nameUrdu: "بی غبارہ", nameEn: "B Balloon", price: 17, category: "kashif" },
  { id: 67, nameUrdu: "موٹر کار", nameEn: "Motor Toy Car", price: 24, category: "kashif" },
  { id: 68, nameUrdu: "چھری", nameEn: "Utility Knife", price: 24, category: "kashif" },
  { id: 69, nameUrdu: "بلب پٹاخہ", nameEn: "Bulb Firecracker", price: 6, category: "kashif" },
  { id: 70, nameUrdu: "لیڈی سموسہ", nameEn: "Lady Samosa Clip", price: 22, category: "kashif" },
  { id: 71, nameUrdu: "سرجیکل بلیک", nameEn: "Surgical Tape / Band Black", price: 155, category: "kashif" },
  { id: 72, nameUrdu: "میلٹ بلون بلیک", nameEn: "Melt Metallic Balloon Black", price: 260, category: "kashif" },
];
